# Generated by Django 6.0.3 on 2026-06-18 23:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.BigAutoField(help_text='unique identifier for the product.', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter the full commercial name of the product', max_length=100, verbose_name='product_name')),
                ('sku', models.CharField(help_text='Unique stock keeping unit(e.g; PROD)', max_length=100, verbose_name='SKU')),
                ('price', models.DecimalField(decimal_places=2, help_text='set the unit price. minimum value is 0.01', max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('quantity', models.PositiveIntegerField(help_text='Current stock level in the warehouse')),
                ('supplier', models.CharField(help_text='Name of the primary vendor', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Products',
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'sku'), name='unique_user_sku')],
            },
        ),
    ]
